// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDerjqeA45CAnRmzt1FuUIJEY73wPYcvNM',
    appId: '1:718254528207:web:98311b2f58429d03eb89ba',
    messagingSenderId: '718254528207',
    projectId: 'pet-care-eece9',
    authDomain: 'pet-care-eece9.firebaseapp.com',
    storageBucket: 'pet-care-eece9.firebasestorage.app',
    measurementId: 'G-335QKGVN4D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDe2vF94uSOXDRVeAPUDQo9lWtOv2pBEYE',
    appId: '1:718254528207:android:66f4660d1ca0a522eb89ba',
    messagingSenderId: '718254528207',
    projectId: 'pet-care-eece9',
    storageBucket: 'pet-care-eece9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDA-2rGn4jIFdYiYBuzyBPaFSAZf1zlK_o',
    appId: '1:718254528207:ios:33bfa83bc49af62eeb89ba',
    messagingSenderId: '718254528207',
    projectId: 'pet-care-eece9',
    storageBucket: 'pet-care-eece9.firebasestorage.app',
    iosBundleId: 'com.example.petCare',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDA-2rGn4jIFdYiYBuzyBPaFSAZf1zlK_o',
    appId: '1:718254528207:ios:33bfa83bc49af62eeb89ba',
    messagingSenderId: '718254528207',
    projectId: 'pet-care-eece9',
    storageBucket: 'pet-care-eece9.firebasestorage.app',
    iosBundleId: 'com.example.petCare',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDerjqeA45CAnRmzt1FuUIJEY73wPYcvNM',
    appId: '1:718254528207:web:4c4415ea42159e19eb89ba',
    messagingSenderId: '718254528207',
    projectId: 'pet-care-eece9',
    authDomain: 'pet-care-eece9.firebaseapp.com',
    storageBucket: 'pet-care-eece9.firebasestorage.app',
    measurementId: 'G-E2P1WQ5H6J',
  );
}
